# Configuration file for SCVURLv1

# Author: Teresita M. Porter
# Date: January 24, 2020

############################################################################
# General pipeline settings
############################################################################

# Indicate number of cores available to run pipeline, snakefile, and configuration file at the command line:
# snakemake --jobs 24 --snakefile snakefile --configfile config.yaml

############################################################################
# Identify raw read files
############################################################################

# This directory contains raw reads (all of them or from just one run)
# Only use compressed fastq files with this pipeline, ex. fastq.gz
# For the standard pipeline, call the directory "data"
raw: "data"

# Indicate 'sample' and 'read' wildcards in raw filenames:
# These files should be in a "data" or "run1", etc. folder
# Sample filename structure,
# 	SITE-CONDITION-REPLICATE_S1_L001_R1_001.fastq.gz
# 	{sample}_L001_R{read}_001.fastq.gz
raw_sample_read_wildcards: "data/{sample}_L001_R{read}_001.fastq.gz"

# SEQPREP sample wildcard and parameters
# These files should be in a "data" or "run1", etc. folder
# Sample,
#	{sample}_L001_R1_001.fastq.gz
raw_sample_forward_wildcard: "data/{sample}_L001_R1_001.fastq.gz"
raw_sample_reverse_wildcard: "data/{sample}_L001_R2_001.fastq.gz"

############################################################################
# Raw read pairing
############################################################################

SEQPREP:
# Phred score quality cutoff
    q: 20
# Minimum overlap length between forward and reverse reads
    o: 25

############################################################################
# Primer trimming
############################################################################

# CUTADAPT parameters for the rbcL-xxx amplicon
# All primers are from Rivera et al., 2008
# FWD primers (5'-3'):
# AGGTGAAGTAAAAGGTTCWTACTTAAA Diat_rbcL_708F_1
# AGGTGAAGTTAAAGGTTCWTAYTTAAA Diat_rbcL_708_2
# AGGTGAAACTAAAGGTTCWTACTTAAA Diat_rbcL_708F_3
# AGGTGAARYWAAAGGTTCWTAYTTAAA <- use this consensus sequence with cutadapt
# REV primers (5'-3'):
# CCTTCTAATTTACCWACWACTG Diat_rbcL_R3_1
# CCTTCTAATTTACCWACAACAG Diat_rbcL_R3_2
# REV primers (reverse complemented for cutadapt):
# CAGTWGTWGGTAAATTAGAAGG Diat_rbcL_R3_1_rc
# CTGTTGTWGGTAAATTAGAAGG Diat_rbcL_R3_2_rc
# CWGTWGTWGGTAAATTAGAAGG <- use this consensus sequence with cutadapt

CUTADAPT_FWD:
    g: "AGGTGAARYWAAAGGTTCWTAYTTAAA"
    m: 150
    q: "20,20"
    mn: 3

CUTADAPT_REV:
    a: "CWGTWGTWGGTAAATTAGAAGG"
    m: 250
    q: "20,20"
    mn: 3

############################################################################
# Dereplication
############################################################################

# Indicate a directory name here that is short and simple with no spaces or weird punctuation
# For the standard pipeline, a good directory name would be the amplicon, ex. "Diat_rbcL", "rbcL"

dir: "rbcL"

############################################################################
# Denoising
############################################################################

# Indicate minimum number of reads per cluster to retain
# Here, remove all singletons and doubletons, retain clusters with 3+ reads

VSEARCH_DENOISE:
    minsize: 3

############################################################################
# Get CDS
############################################################################

# Translate ESVs into all open reading frames
# ORFfinder params
ORFFINDER:

# genetic code
# 5 = invertebrate mitochondrial, see NCBI for additional genetic codes
# 1 = standard code, use this for green plant chloroplast sequences
# 11 = bacterial, archaeal, plant plastid code, use for diatom chloroplast sequences
    g: 1

# ORF start codon to use
# 0 = ATG only
# 1 = ATG and alternative initiation codon (default)
# 2 = any sense codon
    s: 2

# minimum length (default 75, min 30)
    ml: 30

# ignore nested ORFs (true|false)
    n: 'true'

# strand (both|plus|minus)
    strand: 'plus'

# outfiile format
# 0 = list of ORFs in FASTA format (aa)
# 1 = CDS fasta (nt)
# 2 = Text ASN.1
# 3 = Feature table
    outfmt: 1

############################################################################
# ESV x sample table
############################################################################

# VSEARCH params
VSEARCH_TABLE:
# Indicate number of threads to use
# Do not exceed the number of jobs allotted to run the whole pipeline ('jobs' above)
    t: 24


############################################################################
# Taxonomic assignment
############################################################################

# Uses the RDP classifier
# Do not use old RDP classifier v2.2 from conda, install the newer v2.12 from SourceForge https://sourceforge.net/projects/rdp-classifier/
# rbcL Classifier v1 based on sequences mined from GenBank is compatible with the RDP classifier is available from GitHub https://github.com/Hajibabaei-Lab/SCVURL_rbcL_metabarcode_pipeline
# rbcL Diatom Classifier v1 based on curated barcode sequences from INRA (Rimet et al., 2016 Database) is available from https://github.com/terrimporter/rbcLdiatomClassifier

RDP:
    jar: "/path/to/rdp_classifier_2.12/dist/classifier.jar"
    t: "/path/to/rbcLClassifier/v1/mydata/mydata_trained/rRNAClassifier.properties"

############################################################################
# Reformat CSV
############################################################################

# Add amplicon name to Zotu to keep these ids unique when data from many amplicons are combined
# The pattern will prefix the Zotu with the amplicon name
# Ex. sed -e 's/^/amplicon_/g' infile > outfile
# Below, enter the substitution pattern for sed to use (the part in single quotes above) 
# ex. "rbcL_" or "rbcLdiatom_"

SED: 's/^/rbcL_/g'
